name: social_media_manager
description: A premium Social Media Manager offline vault.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  otp: ^3.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  encrypt: ^5.0.3
  share_plus: ^9.0.0          # Untuk share/export file
  file_picker: ^8.0.0         # Untuk memilih file saat import
  path_provider: ^2.1.0       # Untuk mendapatkan direktori temporary

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
