name: social_media_manager
description: A premium Social Media Manager offline vault.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  otp: ^3.1.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  csv: ^5.1.1
  encrypt: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
