name: social_media_manager
description: A premium Social Media Manager offline vault.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  otp: ^3.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
